//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web05.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web05.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra , vui lòng liên hệ MISA để được hỗ trợ.
        /// </summary>
        public static string ErrorException_VN {
            get {
                return ResourceManager.GetString("ErrorException_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không hợp lệ.
        /// </summary>
        public static string ErrorValidate_VN_DateOfBirth {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống,vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorValidate_VN_DuplicateEmployeeCode {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_DuplicateEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string ErrorValidate_VN_Email {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống.
        /// </summary>
        public static string ErrorValidate_VN_EmployeeCode {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được phép để trống.
        /// </summary>
        public static string ErrorValidate_VN_EmployeeName {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không hợp lệ.
        /// </summary>
        public static string ErrorValidate_VN_IdentityDate {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_IdentityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại di động đã có trong hệ thống.
        /// </summary>
        public static string ErrorValidate_VN_TelephoneNumberExit {
            get {
                return ResourceManager.GetString("ErrorValidate_VN_TelephoneNumberExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_EN_Female {
            get {
                return ResourceManager.GetString("Gender_EN_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_EN_Male {
            get {
                return ResourceManager.GetString("Gender_EN_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Gender_EN_Other {
            get {
                return ResourceManager.GetString("Gender_EN_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Gender_VN_Female {
            get {
                return ResourceManager.GetString("Gender_VN_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Gender_VN_Male {
            get {
                return ResourceManager.GetString("Gender_VN_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Gender_VN_Other {
            get {
                return ResourceManager.GetString("Gender_VN_Other", resourceCulture);
            }
        }
    }
}
